name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with: 
          node-version: 12.x
          
      - name: Install dependencies
        run: |
          cd ./backend 
          yarn
        
      - name: Run a build
        run:  |
          cd ./backend 
          yarn build
          
      - name: Copy dist to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./backend/dist"
          target: "test"      
